"""empty message

Revision ID: 3bfc81510c43
Revises: 2505ad08a7d0
Create Date: 2020-08-12 12:12:22.439674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfc81510c43'
down_revision = '2505ad08a7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'youtube_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('youtube_id', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
